### ISSUE TITLE
Feature: create Layout component

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/m3ntorship.com-v2#27]
**Story**
create Layout component to wrap the application with

**Tasks**
- [x] create HOC folder in components folder and add the Layout component in this folder
- [x] use this component in `index.tsx` file to wrap the application with
- [x] add `min-height` of 100vh to the layout and `max-width` of 1216px (add this value in tailwind.config file)
- [x] add this background color which is in [Figma](https://www.figma.com/file/5KpDnPPmrZhudGESduPhq3/M3ntorship-Website?node-id=153%3A3113) to the layout
- [x] consider adding padding also for different screens and use [Figma](https://www.figma.com/file/5KpDnPPmrZhudGESduPhq3/M3ntorship-Website?node-id=153%3A3113) values
