### ISSUE TITLE
Testimonials Page - initial creation

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/m3ntorship.com-v2#80]
**Story**
the initial sections which will be added to Testimonials Page in [Figma design](https://www.figma.com/file/5KpDnPPmrZhudGESduPhq3/M3ntorship-Website?node-id=1347%3A9705)

**Tasks**
- [x] Add **DefaulLayout** component and display it with **Navbar** and **Footer**
- [x] Add **EnrollSection** component to `shared` folder and import it in Testimonials Page
- [ ] Add SEO content :
   * Title - Testimonials
   * Description - ?????
   * Image - Will be the Testimonials [Hero bg](https://www.figma.com/file/5KpDnPPmrZhudGESduPhq3/M3ntorship-Website?node-id=1347%3A9705)

**Acceptance criteria**
the initial screen should be implemented to prepare for other sections
![Screenshot from 2022-09-26 23-49-26](https://user-images.githubusercontent.com/52901348/192386970-9f27a4b4-0b15-4f58-a806-7357f742ec00.png)
![Screenshot from 2022-09-26 23-49-36](https://user-images.githubusercontent.com/52901348/192386964-100158ca-4035-4233-b2ff-3f5126baefab.png)
